# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'LoggingInToGithub' do
    pod 'AFNetworking'
    pod 'AFOAuth2Manager'
end

target 'LoggingInToGithubTests' do

end

